# Generated by Django 3.2.15 on 2023-09-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basic_User',
            new_name='Customed_User',
        ),
        migrations.RenameField(
            model_name='customed_user',
            old_name='user_name',
            new_name='username',
        ),
    ]
