# Generated by Django 3.2.15 on 2023-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=12)),
                ('phone', models.IntegerField()),
                ('organization', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
