# Generated by Django 3.2.15 on 2023-10-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20231007_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptuser',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
