# Generated by Django 3.2.15 on 2023-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_gptuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
