# Generated by Django 3.2.15 on 2023-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_gptuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptFormUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=20)),
            ],
        ),
    ]
