# Generated by Django 3.2.15 on 2023-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_gptformuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptformuser',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gptformuser',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='gptuser',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gptuser',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
