# Generated by Django 3.2.15 on 2023-10-11 04:36

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_uploadpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(storage=app01.models.OverwriteStorage(), upload_to='uploads/'),
        ),
    ]
