# Generated by Django 3.2.15 on 2023-10-11 16:38

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20231011_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptformuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='uploadpdf',
            name='file',
            field=models.FileField(upload_to=app01.models.rename_file),
        ),
    ]
