# Generated by Django 3.2.15 on 2023-10-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20231012_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptformuser',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gptformuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='gptformuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
